---

- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - fault-tox-linters
        - fault-tox-pep8
        - fault-tox-pylint
        - fault-rest-api-py39
    gate:
      jobs:
        - fault-tox-linters
        - fault-tox-pep8
        - fault-tox-pylint
        - fault-rest-api-py39
    post:
      jobs:
        - stx-fault-upload-git-mirror

- job:
    name: fault-tox-linters
    parent: openstack-tox-linters
    description: |
      Run tox linters on specific nodeset
    nodeset: debian-bullseye

- job:
    name: fault-tox-pep8
    parent: openstack-tox-pep8
    description: |
      Run pep8 tests (flake8) on specific nodeset
    nodeset: debian-bullseye

- job:
    name: fault-rest-api-py39
    parent: tox-py39
    description: |
      Run py39 test for fm-rest-api
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/utilities
    vars:
      bindep_profile: test py39
      python_version: 3.9
      tox_envlist: py39
      tox_extra_args: -c fm-rest-api/fm/tox.ini

- job:
    name: fault-tox-pylint
    parent: tox
    description: |
      Run pylint for python files in fault
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
    vars:
      tox_envlist: pylint

- job:
    name: stx-fault-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/fault to
      github.com/starlingx/fault
    vars:
      git_mirror_repository: starlingx/fault
    secrets:
      - name: git_mirror_credentials
        secret: stx-fault-github-secret3
        pass-to-parent: true

- secret:
    name: stx-fault-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - mrx/g/aZY7sq7qaXgYGOk7NtVQDYRSZdbJg9t7Jfpe2uB/4mSnBubg9MDFXUHR1MXpQ/T
          IgsqgrLabFJa61jRc/zIMnS/Wmb7UH8byYJYblSxH37s+VGTF3VmYk0Euyakch1xc+a2O
          oFUJD/HMZIm/2ODdMKwZDAhfsH+q4b5d6Yfz6ruGGwrTdaGI1tvrVqP4j+WIT1jrh+m2Y
          3pvNVkrMA0vluF1CCRdcjR4mHiBaP2XM8Am8PPN/4agyzlXpEFW83vbxivkW2sYpnRLxM
          GZ/0nPlqNdFf8+yk38Ax2a2ZinafNHkjXZElz31uv+/Z0EcI5yaaZJ1nQgDOzxPAfhPjy
          E4LYau0KbCly8Sx+/GeqgELPprbz9j5FqzabCS5hBfishG545WMYIsF5Grs261vMe2dzZ
          i/VVt63/3gRjk/Mh31aaaVfIDAmvIzgu+Bjx0VXK36k27AYR8QCxKajRMaWdDlQO3ijEZ
          k1hx2v4CBXHXONH4DiQRJElQMR2U7PjSDoMMRaoeKujH1iD84b5XVAOvi+7XnRpGwkXMf
          3GYTJLaschOff43QohiOmGv070v41W19TAWK8DpGWWmJwNjQBoQYLraNncG2cmeO+eLma
          1Z/LDxgV7HkvJ/RpJh7Rmw87xLpUeyPXZiyCYP5nh6Vn2U5ES4hHmkBecsDUro=
        - aNqY6If2hZHFUx17OLE4hZ3etK5TpxtPAiDA/EgTmwpvudJkfflIg3l26Mm8AEbRW7VEp
          8UhR189Stgh49Qyy664Fj37ovb+GiVDFD7jZbgwWFd+rGYKFKWuF2pI5tkWXwMNwHUxHL
          xY78CU1WWWN/6Whg8EIy1Pe74/awHfC7w8F8m9bTEPcdo/cFusAcEBFc1AKrpoE2dyPjK
          cebJ0HY8haP6CLKT2608jsFlyrEeR6kKCm79rdJpn77WEPSfbGNRmYR2ySdeFDmOcQo9y
          WN93AQB6nSqmJGoZLLhNbiDr+CKN2ftNrdd4QizFwYXBNHIDpyE30q3S4KJWlAzRJuFmz
          WAJ6KQlhFVWLRaDGvFu6OACuVNrPanptujhs2uGvfhlPOPjAgh0KfH2Rq+05N6aGtGiQ9
          Eso8hhhSCkAKLOVcHT7MhASD1WH/EA3Fn1Aw/gvas4OAlqQF7PnaOnTJCHVgkyysbhQVE
          1HoAsDUjium73msxdGqzEKo2v9l1RPCnpFQ61003Gc5Tft/lx50rdosD3MZUXqxkuIrNX
          Z3lmygDoYp/JPgLcZVkhgLQF70KNWVsKv8qumcB8SFZKhxCD8axFLq8qoi9jvobUplge9
          OH7jzj2kZwFERZGEpkCB0jgyP8ebRXjFV3Q75EG9/AmsA8kDKqdLLNlR4ROGNc=
        - KEp+pKPxYoI2eTi6VR2thE0Wl2HqaeRWTNYQZbboroLgWNqlyeAyzxzooeHCVcooihywr
          y+9UIqDmL2DjrIe7KLXqemtO+t8sztFwio3PKJRttVqQzi9swPur3Qu6xDwu9AThoN7zo
          qTx5guAEcv9nexHo86LlIzhJW3hW4nau1MEsXTtzvXg/XfWwife3QCU9DbaoY9m8wJ3e4
          eyyazUqj3AtnVYnTvo38DBZ7tg1mFbewxP5c52yovG86sJ0dKQkBTleP0OTBVRrSdY/HZ
          njMAhisd5WZFCF+EUTiNU1tIg1G8XkTIbevEQqHEuAc3oWfY7mvgq2mkO0m5wVtfmt7l8
          J6Wo6S7c5b4O0V1Lz+qUBq/XKwjgoT7nNiAbzuEU6OOmWNxLpCaJrcXklM2FWdUnw0gHr
          TARaS8JRd9GdUDxPVVLuCilfQOiVM9daZFq2bScLyLBeRRtIhXh+zn3G9ieaiZ2ErbOF9
          F42KJ6LGCK1fWojv2svbuHUiPK4/VMyCUiVku0Rw5GI8q/hsWWhFXgjc/K+Cr72Kzh4G/
          R3G4nkywzzgM1wT6NInoAuBFq/FJp6cfQf+g77y/hmK/XwpbyppDPDQh+FVGC/YTEZ2em
          J17rtE9HKshvJMPkXOKTt24eStYRZ/ZqHnKS44Jm25BqzZ7ZlRN2D4sMtr+ek4=
        - AYLA75XO9s/AAl0O3N7VwWYjdhu3woXtrqgLk/ekjraYZwXUBn91ofcLZUoxQtcgJe40D
          8cZcb9q5YScNKCFpnSd9vcNlF006kmRIDglRwlCr6uAJZInK1qTGVmcE/2aNoJ+NrEvVP
          dIPPOnyojvLVwmWyYH43erf19f0YrrZq/R+rjq7KfhmbE83/8IRto+8L7qpM3pwUVWS/3
          RoMoTP70n2lpFrU2cdJttVumnfKjMTzQmkyTUWA9rno9XDamW7puXCqUyIHSj+VXxjhfb
          7B5GcrhfSimGg19hlzygOi4D/kXrHpmkcFeJWda+E6pI5EV536j4lishcKCTz3UJuw6i4
          eIN7vUb6x/P7a27pRDAT0F0x9Q0vaCATrrx9DegDM/KnzF7bPM5ZzqLzuVBLCbl8+6tXd
          RmeGMW0QEb5XLQIxnN7WyOyufgER7f0wWwL6kL3pzmvQcMsCFvcJ8s2kSI/mpsISC2zi0
          sn4o4whaNtM75/2RsxtzNJdTrJ8Lq0XKXt9x0Eb9cvcSDEWggF2z1yCRznrhaqvmcYcZn
          gs6M4OIbDPKmhmiH1FszNAlj9HL13N4xcH29lZoHMbBqL8mad8tfqtKhfPJU9bthnggG3
          MqKM4VEBafKAhseA2tN6VXrbK92CcGiud3jKVeitDKpqAvmix0jptiSNo7ovDc=
        - VD0uauey6UE3xdmCOleMNDY1SckT6bdLbkK5FwOnry9GYl8K3hPKYZwfeDnq5OX/6Ju/4
          yM+flqji7H89CMuqwfy/Zv7jvmZhUs7ThRE6kHJczP6/SHM0wmTJLqTXqI5cSbyB1pWaa
          iWigaiqCTdlaqzBGbVmPfKstWjRCgCwlnvhh/3hTV3j35prhZo3mLz1+XF9UQD/uboHPD
          bCU4bOTpRTB6I6wXMZyn/viNZ0FxQ8SIgnC39eMqokGqh+4ei+6yO3VAu6V3EAXfGIqhW
          yKdY/i4uv07L3xvkB0cV8pQkYeoDvK9nEn9fBxjabWdZqToMtpoWqwcnPsX6N/aJ1Q53H
          bmpBu2kt+mOpzfHadWxHKONzAjqDyVEbmfAWjmN2rNK8nTZmC+CtTaWvrynU6n2hUia9X
          y4WcOTfnJkRzP5aESjoUtL881edpJUiDRJQhaMkaO+ld6VTtFI8kEgIEupkHWeU1VjZF3
          Hg9iLXtRR9qC2q6H/B9V7XwY2GKSkrTvqyOMUTC2UpvjGIlAq+zC7AzI8PVSV6LfNNYDm
          sdTzsTdpiYC9+dEzNqP9JBvsAs4CqNtKDNGaCB8ILlLP8jCYwexoQ29AV+WLsTqrKgGpi
          LsIm+NFSstuLveRwruMcakScbVYl2LUq+QJO25a0UMzIT42ZMn/mcHdMH1iHpQ=
        - FTCmqo3/ivyoxtXA+Tg0VjLVKboCVcsgjBHNNkwGv8S8rsU4TSVrM4PLX4jV49zZ8o1EK
          J5+5Omh5BcpZ2L4f4pctPYy9+M7GNCOVXrXyUCXXUbuztPCvQbhxBf1PwOKKlu/AKQ2hW
          ds6X5uUi8jThP1F1V2DhjY7r9t1FGUq0x5H2uhegyxS3W+y6mWSaOX8qL/RMkggMzCStU
          RPdSBBax6k35vEQDf2cJRc80ina2kEj2Q/mi6wNJM67M7P/rvsdyiAoYwFgyMuhoffeRD
          WjEa2tp0bnLEsEB9mO6dswuWePXvjv5N3dTruTvpNPE0LVfA0QpVah/IX83AEg15s0lFw
          5GpRUUa323WUd/Li2l5lIXd8cG8cZ5E3wd+5NNCUgk2mf/HoM64hThniuxjy2TcM00C0+
          JhBhl0OkGLqrzHsjTteQXycJZMdInRaVlZA1rlMcKAPXMuv40VtCiINRDtv0eSDglebAm
          5hNuqK3XxZHYuFQcjgNxYjVMc9Uf4O8owDbRvVfef2kQhK2yfDmVeCgtAGqd2POdQ+lnK
          pxwl0QZpolDmlBK0m85J0VFAcuwzBRnVKLC/kHs7940WRn9Ddu/FNiKw22mCcRdoggWeV
          A3VM/9Y9bYMLEZ0PMCTa1S1F+1zNFcTbpokEOQjS0XqcTq20ReBiyN1hWUJd90=
        - wkjLGBHK5LFUKeLmKr5oum7gtd5XHdN+mk6jGPc+r0LZWOnYIxGPld45UVqLjDO1o/5jc
          /yQMisIOZ9ac2QVJZiDLoBn6u4eA0Wtbe4YM9wR8nIjBty5c9u6EL+CxXw5aBMEpnJXKj
          MCtkOztkH3vXlqC/v6tMWF4bmfv2X73JdkHb2BD+Ivbycy2jAfsbjcpWbgJCOfaCh4H3u
          RFFmPnjO3cxywRaYWj8u7U4r7+osSz1hDZVG0C1XnC7PDe5dEP86BNm/i3vjVUam3z74A
          PwZOepHHs9NHLmmvbaQYOQ+xMjlnkp/bYqAHewfVQYCOD12H7+Sk6JvDoFgF31BTbbUPc
          L1/Kh+tXmzvTsv9EdR0hYXKNSwcczH4pkUDP95wBHo1iRq9QfPc7T4KahdKjBSCOyJv7o
          Grxh2L2wsW2SGcBM1K4TFTbQgehnctxng1HIO35cezVi92fBOcXx3EACfrK1Mp4Oi7Yl2
          64aX3OBojwptTJeXAT4jodcC33H4QYTycp/+aX1d64yb33aqwaf4xt/A2nQ+QWP7e/bJv
          majKLZFLg9Ii4zzhb5Saqf588tNlpqHmbBVHvTXrv5i4qMVQ4lkxzS6HbgbaVHiKEyLp9
          msuhPi1O+eSNzemjZ4hZGp9BqXPnAbWaBSb8RKCIkprKivYDXn3pBUljyjzZvU=
